version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-password}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB:-handmadeshop}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - handmadeshop-net

volumes:
  db_data:

networks:
  handmadeshop-net:
    name: handmadeshop-net
    driver: bridge
